import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy · Folio',
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="font-serif text-[18px] font-bold text-stone-900 dark:text-stone-50 mb-3 tracking-tight">
        {title}
      </h2>
      <div className="space-y-3 text-[14px] text-stone-600 dark:text-stone-400 leading-[1.75]">
        {children}
      </div>
    </section>
  );
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-stone-50 dark:bg-stone-950">

      {/* Simple header */}
      <header className="border-b border-stone-200 dark:border-stone-800">
        <div className="h-[3px] bg-stone-900 dark:bg-stone-100" />
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link href="/" className="font-serif text-[20px] font-bold tracking-tight text-stone-900 dark:text-stone-50 hover:opacity-75 transition-opacity">
            Folio
          </Link>
          <Link href="/" className="font-sans text-[11px] text-stone-400 dark:text-stone-500 hover:text-stone-700 dark:hover:text-stone-300 transition-colors">
            ← Home
          </Link>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-4 sm:px-6 py-12">

        <div className="mb-10">
          <p className="font-sans text-[10px] tracking-widest uppercase text-stone-400 dark:text-stone-500 mb-3">
            Legal
          </p>
          <h1 className="font-serif text-[30px] font-bold text-stone-900 dark:text-stone-50 tracking-tight mb-2">
            Privacy Policy
          </h1>
          <p className="text-[13px] font-sans text-stone-400 dark:text-stone-500">
            Last updated: 5 March 2026
          </p>
        </div>

        <Section title="Who we are">
          <p>
            Folio (&quot;the Service&quot;, &quot;we&quot;, &quot;us&quot;) is operated by an individual based in the United Kingdom. For data protection purposes under UK GDPR, we are the controller of your personal data.
          </p>
          <p>
            To contact us about your data, email{' '}
            <a href="mailto:feedbackfolio@gmail.com" className="underline underline-offset-2 text-stone-700 dark:text-stone-300">
              feedbackfolio@gmail.com
            </a>.
          </p>
        </Section>

        <Section title="What data we collect">
          <p>We collect the minimum data necessary to provide the Service:</p>
          <ul className="list-disc list-inside space-y-2 pl-2">
            <li>
              <span className="font-medium text-stone-700 dark:text-stone-300">Account data</span> — your email address and name, collected when you create an account via Clerk.
            </li>
            <li>
              <span className="font-medium text-stone-700 dark:text-stone-300">Subscription status</span> — whether you have an active paid subscription. Payment details (card number, billing address) are processed directly by Stripe and never stored by us.
            </li>
            <li>
              <span className="font-medium text-stone-700 dark:text-stone-300">Saved content</span> — bookmarks and personal notes you save within the Service, stored in our database.
            </li>
            <li>
              <span className="font-medium text-stone-700 dark:text-stone-300">Server logs</span> — standard request logs generated by our hosting provider (Vercel), including IP addresses and pages visited. These are retained for up to 30 days.
            </li>
          </ul>
          <p>
            We do not use third-party analytics tools (such as Google Analytics). We do not sell your data to anyone.
          </p>
        </Section>

        <Section title="How we use your data">
          <p>We use your data solely to:</p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li>Create and manage your account</li>
            <li>Process and manage your subscription</li>
            <li>Send transactional emails (e.g. welcome email, payment receipts)</li>
            <li>Provide and improve the Service</li>
            <li>Respond to support requests</li>
          </ul>
          <p>
            Our legal basis for processing is contract performance (providing the service you signed up for) and, where applicable, legitimate interests.
          </p>
        </Section>

        <Section title="Third-party services">
          <p>We use the following trusted third-party services to operate the Service:</p>
          <ul className="list-disc list-inside space-y-2 pl-2">
            <li>
              <span className="font-medium text-stone-700 dark:text-stone-300">Clerk</span> — authentication and account management. Stores your email and name.
            </li>
            <li>
              <span className="font-medium text-stone-700 dark:text-stone-300">Stripe</span> — payment processing. Handles all card details under PCI-DSS compliance. We receive only subscription status from Stripe.
            </li>
            <li>
              <span className="font-medium text-stone-700 dark:text-stone-300">Upstash (Redis)</span> — cloud database for subscription records, bookmarks, and cached content.
            </li>
            <li>
              <span className="font-medium text-stone-700 dark:text-stone-300">Vercel</span> — hosting and serverless infrastructure. Processes request data as part of serving the site.
            </li>
            <li>
              <span className="font-medium text-stone-700 dark:text-stone-300">Resend</span> — transactional email delivery.
            </li>
            <li>
              <span className="font-medium text-stone-700 dark:text-stone-300">ElevenLabs / Anthropic / Tavily</span> — used for generating briefing content and audio. No personal data about you is sent to these services.
            </li>
          </ul>
        </Section>

        <Section title="Cookies">
          <p>
            We use a session cookie set by Clerk to keep you signed in. This cookie is strictly necessary for the Service to function and does not track you across other websites.
          </p>
          <p>
            We do not use advertising cookies, tracking pixels, or third-party analytics cookies.
          </p>
        </Section>

        <Section title="Data retention">
          <p>
            We retain your account data for as long as your account is active. If you request deletion of your account, we will delete your personal data within 30 days, except where we are required to retain records for legal or financial reasons (for example, Stripe transaction records).
          </p>
        </Section>

        <Section title="Your rights (UK GDPR)">
          <p>You have the right to:</p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li>Access the personal data we hold about you</li>
            <li>Correct inaccurate data</li>
            <li>Request deletion of your data</li>
            <li>Object to or restrict our processing</li>
            <li>Data portability (receive your data in a portable format)</li>
            <li>Withdraw consent where processing is based on consent</li>
          </ul>
          <p>
            To exercise any of these rights, contact us at{' '}
            <a href="mailto:feedbackfolio@gmail.com" className="underline underline-offset-2 text-stone-700 dark:text-stone-300">
              feedbackfolio@gmail.com
            </a>. We will respond within 30 days. You also have the right to lodge a complaint with the Information Commissioner&apos;s Office (ICO) at{' '}
            <a href="https://ico.org.uk" target="_blank" rel="noopener noreferrer" className="underline underline-offset-2 text-stone-700 dark:text-stone-300">
              ico.org.uk
            </a>.
          </p>
        </Section>

        <Section title="Changes to this policy">
          <p>
            We may update this policy from time to time. Material changes will be communicated by email or by a notice on the Service. The date at the top of this page reflects the most recent update.
          </p>
        </Section>

      </main>
    </div>
  );
}
